# Generated by Django 6.0.2 on 2026-03-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amnt', models.FloatField(verbose_name='Montant du prêt')),
                ('person_income', models.FloatField(verbose_name='Revenu annuel')),
                ('loan_int_rate', models.FloatField(verbose_name="Taux d'intérêt")),
                ('debt_ratio', models.FloatField(verbose_name="Taux d'endettement (%)")),
                ('person_age', models.PositiveIntegerField(verbose_name='Âge')),
                ('person_emp_length', models.FloatField(verbose_name='Ancienneté emploi')),
                ('cb_person_cred_hist_length', models.FloatField(verbose_name='Historique de crédit')),
                ('loan_grade', models.CharField(blank=True, max_length=10, verbose_name='Grade de crédit')),
                ('person_home_ownership', models.CharField(blank=True, max_length=30, verbose_name='Situation logement')),
                ('loan_intent', models.CharField(blank=True, max_length=50, verbose_name='Objet du prêt')),
                ('cb_person_default_on_file', models.CharField(blank=True, max_length=5, verbose_name='Antécédent de défaut')),
                ('probability', models.FloatField(verbose_name='Probabilité de défaut')),
                ('decision', models.CharField(choices=[('ACCEPT', 'Accepté'), ('REVIEW', 'À examiner'), ('REJECT', 'Refusé')], max_length=10, verbose_name='Décision')),
                ('risk', models.CharField(max_length=20, verbose_name='Niveau de risque')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de scoring')),
            ],
            options={
                'verbose_name': 'Historique de scoring',
                'verbose_name_plural': 'Historiques de scoring',
                'ordering': ['-created_at'],
            },
        ),
    ]
