# Generated by Django 6.0.2 on 2026-03-11 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorehistory',
            name='client_number',
            field=models.CharField(default='CLIENT_INCONNU', max_length=50, verbose_name='Numéro client'),
            preserve_default=False,
        ),
    ]
