# Generated by Django 5.1.7 on 2026-08-18 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring', '0002_scorehistory_client_number'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='scorehistory',
            name='analyst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_history', to=settings.AUTH_USER_MODEL, verbose_name='Analyste'),
        ),
        migrations.AddField(
            model_name='scorehistory',
            name='model_version',
            field=models.CharField(blank=True, max_length=100, verbose_name='Version du modèle'),
        ),
        migrations.AddField(
            model_name='scorehistory',
            name='request_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP'),
        ),
        migrations.AddField(
            model_name='scorehistory',
            name='source',
            field=models.CharField(choices=[('WEB', 'Formulaire web'), ('API', 'API')], default='WEB', max_length=20, verbose_name='Origine de la demande'),
        ),
        migrations.AlterField(
            model_name='scorehistory',
            name='client_number',
            field=models.CharField(db_index=True, max_length=50, verbose_name='Numéro client'),
        ),
        migrations.AlterField(
            model_name='scorehistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Date de scoring'),
        ),
        migrations.AlterField(
            model_name='scorehistory',
            name='decision',
            field=models.CharField(choices=[('ACCEPT', 'Accepté'), ('REVIEW', 'À examiner'), ('REJECT', 'Refusé')], db_index=True, max_length=10, verbose_name='Décision'),
        ),
    ]
